/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "PasskeyMe Developer Documentation",
  "tagline": "Authentication made simple with passkeys and OAuth",
  "favicon": "img/passkeyme-logo-short-removebg-preview.ico",
  "url": "https://docs.passkeyme.com",
  "baseUrl": "/",
  "organizationName": "passkeyme",
  "projectName": "passkeyme-docs",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/passkeyme/passkeyme/tree/main/docs/",
          "showLastUpdateTime": true,
          "showLastUpdateAuthor": true,
          "breadcrumbs": true,
          "sidebarCollapsible": true,
          "sidebarCollapsed": false
        },
        "blog": {
          "path": "./blog",
          "routeBasePath": "blog",
          "include": [
            "*.md",
            "*.mdx"
          ],
          "blogTitle": "PasskeyMe Developer Blog",
          "blogDescription": "Updates, tutorials, and insights about passkey authentication and OAuth integration",
          "showReadingTime": true,
          "postsPerPage": 10,
          "blogSidebarCount": "ALL",
          "blogSidebarTitle": "All posts",
          "feedOptions": {
            "type": "all",
            "copyright": "Copyright © 2025 PasskeyMe, Inc."
          }
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/passkeyme-logo-short-green-removebg-preview.png",
    "navbar": {
      "title": "PasskeyMe",
      "logo": {
        "alt": "PasskeyMe Logo",
        "src": "img/passkeyme-logo-short-green-removebg-preview.png",
        "srcDark": "img/passkeyme-logo-short-green-removebg-preview.png"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Documentation"
        },
        {
          "to": "blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "to": "https://passkeyme.com/apidocs",
          "label": "API Reference",
          "position": "left"
        },
        {
          "href": "https://passkeyme.com/dashboard",
          "label": "Dashboard",
          "position": "right"
        },
        {
          "href": "https://passkeyme.com",
          "label": "Main Site",
          "position": "right"
        },
        {
          "href": "https://github.com/passkeyme/passkeyme",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Documentation",
          "items": [
            {
              "label": "Getting Started",
              "to": "/docs/getting-started/quick-start"
            },
            {
              "label": "API Reference",
              "href": "https://passkeyme.com/apidocs"
            },
            {
              "label": "SDKs",
              "to": "/docs/sdks/overview"
            }
          ]
        },
        {
          "title": "Product",
          "items": [
            {
              "label": "Dashboard",
              "href": "https://passkeyme.com/dashboard"
            },
            {
              "label": "Main Site",
              "href": "https://passkeyme.com"
            },
            {
              "label": "Pricing",
              "href": "https://passkeyme.com/pricing"
            }
          ]
        },
        {
          "title": "Support",
          "items": [
            {
              "label": "Contact",
              "href": "https://passkeyme.com/contact"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/passkeyme/passkeyme"
            },
            {
              "label": "Status",
              "href": "https://status.passkeyme.com"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 PasskeyMe, Inc. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "json",
        "javascript",
        "typescript",
        "jsx",
        "tsx"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "themes": [
    "@docusaurus/theme-mermaid"
  ],
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
